spring:
  application:
    name: email-sender-service-test

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.halmber.emailsenderservice.model.dto.EmailMessageDto
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  mail:
    host: smtp.test.com
    port: 587
    username: test@test.com
    password: test-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

kafka:
  topics:
    emailSend: emailSend

scheduler:
  fixed.rate: 300000

scheduling:
  enabled: false

logging:
  level:
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.elasticsearch: WARN
    com.halmber: DEBUG